### PR TITLE
Fix title centering on landing page

### PR DESCRIPTION
**Pull request by EricLScace**
Why: style rules not being applied properly

What: Also discovered & repaired Font Awesome loading
.gitignore updated to allow font files to be captured in repo

Editorials: n/a

Testing: page loads properly locally

Consequences: n/a

references #34

### CODE REVIEW

**Comment by EricLScace** [comment]
wrong target branch!

**Comment by EricLScace** [comment]
still not letting me select the merge target branch properly.

**Comment by EricLScace** [comment]
PLEASE REJECT THIS PULL REQUEST. Then I can try to create a fresh one that has the right target branch of development for the merge.

**Comment by EricLScace** [comment]
Fixed the target branch!

**Review by lisawilliams — APPROVED** [review]

**Pull request merged**
